apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storagealerts.alerts.monstorak.org
spec:
  group: alerts.monstorak.org
  names:
    kind: StorageAlert
    listKind: StorageAlertList
    plural: storagealerts
    singular: storagealert
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            prometheus:
              properties:
                label:
                  additionalProperties:
                    type: string
                  type: object
                namespace:
                  type: string
              type: object
            storage:
              items:
                properties:
                  namespace:
                    type: string
                  provider:
                    type: string
                  version:
                    items:
                      type: string
                    type: array
                type: object
              type: array
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
