apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-noobaa-rules
  namespace: default
spec:
  groups:
  - name: bucket-quota-alert.rules
    rules:
    - alert: NooBaaBucketQuotaWarning
      annotations:
        description: A NooBaa bucket is approaching its quota, usage is more than
          85%
        message: A NooBaa Bucket Is Approaching Its Quota
        severity_level: warning
        storage_type: NooBaa
      expr: |
        noobaa_bucket_quota{} > 0.85
      labels:
        severity: warning
  - name: resource-state-alert.rules
    rules:
    - alert: NooBaaResourceErrorState
      annotations:
        description: A NooBaa resource is in error state for more than 2m.
        message: A NooBaa Resource Is In Error State
        severity_level: error
        storage_type: NooBaa
      expr: |
        noobaa_resource_health_status{} > 1
      for: 2m
      labels:
        severity: critical
