apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monstorak
  namespace: storage-monitoring
  labels:
     app: monstorak-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monstorak-operator
  template:
    metadata:
      labels:
        app: monstorak-operator
    spec:
      serviceAccountName: monstorak
      containers:
      - image: "quay.io/monstorak/monstorak-operator:a973958"
        imagePullPolicy: Always
        name: monstorak
        env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "monstorak-operator"
