apiVersion: apps/v1
kind: Deployment
metadata:
  name: monstorak
spec:
  replicas: 1
  selector:
    matchLabels:
      name: monstorak
  template:
    metadata:
      labels:
        name: monstorak
    spec:
      serviceAccountName: monstorak
      containers:
        - name: monstorak
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - monstorak
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "monstorak"
