kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monstorak
subjects:
- kind: ServiceAccount
  name: monstorak
roleRef:
  kind: Role
  name: monstorak
  apiGroup: rbac.authorization.k8s.io
